-- 25 Fake Students
INSERT INTO public.students (first_name, last_name, middle_name, email, phone_number, street_address, city, state, zip_code, major, concentration, department, academic_year, enrollment_status, gpa, residency, financial_class, first_gen, race, ethnicity, gender, disability, military, opted_in) VALUES
('James', 'Thornton', 'Allen', 'codeminers4tw@gmail.com', '555-201-4321', '142 Maple St', 'Columbus', 'OH', '43201', 'Computer Science', 'Cybersecurity', 'Engineering', 'Junior', 'Full-Time', 3.45, 'In-State', 'Low Income', TRUE, 'White', 'Non-Hispanic', 'Male', FALSE, FALSE, TRUE),
('Maria', 'Delgado', 'Lucia', 'codeminers4tw@gmail.com', '555-202-8765', '87 River Rd', 'San Antonio', 'TX', '78201', 'Nursing', 'Pediatrics', 'Health Sciences', 'Sophomore', 'Full-Time', 3.72, 'In-State', 'Low Income', TRUE, 'White', 'Hispanic', 'Female', FALSE, FALSE, TRUE),
('DeShawn', 'Williams', 'Marcus', 'codeminers4tw@gmail.com', '555-203-5544', '310 Oak Ave', 'Atlanta', 'GA', '30301', 'Business Administration', 'Finance', 'Business', 'Senior', 'Full-Time', 2.95, 'In-State', 'Middle Income', FALSE, 'Black', 'Non-Hispanic', 'Male', FALSE, FALSE, TRUE),
('Priya', 'Patel', 'Anita', 'codeminers4tw@gmail.com', '555-204-3312', '55 Birch Ln', 'Edison', 'NJ', '08817', 'Biology', 'Pre-Med', 'Sciences', 'Freshman', 'Full-Time', 3.91, 'In-State', 'Middle Income', FALSE, 'Asian', 'Non-Hispanic', 'Female', FALSE, FALSE, TRUE),
('Tyler', 'Nguyen', NULL, 'codeminers4tw@gmail.com', '555-205-7890', '201 Pine St', 'Portland', 'OR', '97201', 'Environmental Science', NULL, 'Sciences', 'Junior', 'Full-Time', 3.10, 'In-State', 'Low Income', TRUE, 'Asian', 'Non-Hispanic', 'Male', FALSE, FALSE, TRUE),
('Aaliyah', 'Jackson', 'Renee', 'codeminers4tw@gmail.com', '555-206-4423', '98 Elm St', 'Detroit', 'MI', '48201', 'Social Work', NULL, 'Social Sciences', 'Senior', 'Part-Time', 3.55, 'In-State', 'Low Income', TRUE, 'Black', 'Non-Hispanic', 'Female', TRUE, FALSE, TRUE),
('Connor', 'O''Brien', NULL, 'codeminers4tw@gmail.com', '555-207-6654', '77 Cedar Rd', 'Boston', 'MA', '02101', 'Political Science', 'Public Policy', 'Social Sciences', 'Sophomore', 'Full-Time', 2.78, 'In-State', 'High Income', FALSE, 'White', 'Non-Hispanic', 'Male', FALSE, FALSE, FALSE),
('Fatima', 'Al-Hassan', 'Zara', 'codeminers4tw@gmail.com', '555-208-2231', '450 Walnut Ave', 'Dearborn', 'MI', '48124', 'Computer Science', 'AI', 'Engineering', 'Junior', 'Full-Time', 3.88, 'In-State', 'Low Income', TRUE, 'Middle Eastern', 'Non-Hispanic', 'Female', FALSE, FALSE, TRUE),
('Brandon', 'Lee', 'Scott', 'codeminers4tw@gmail.com', '555-209-9987', '33 Spruce St', 'Seattle', 'WA', '98101', 'Mechanical Engineering', NULL, 'Engineering', 'Senior', 'Full-Time', 3.22, 'In-State', 'Middle Income', FALSE, 'Asian', 'Non-Hispanic', 'Male', FALSE, TRUE, TRUE),
('Sofia', 'Martinez', 'Elena', 'codeminers4tw@gmail.com', '555-210-3345', '19 Poplar Blvd', 'Miami', 'FL', '33101', 'Education', 'Special Education', 'Education', 'Junior', 'Full-Time', 3.67, 'In-State', 'Low Income', TRUE, 'White', 'Hispanic', 'Female', FALSE, FALSE, TRUE),
('Elijah', 'Brown', NULL, 'codeminers4tw@gmail.com', '555-211-5566', '88 Hickory Dr', 'Chicago', 'IL', '60601', 'Criminal Justice', NULL, 'Social Sciences', 'Freshman', 'Full-Time', 2.60, 'In-State', 'Low Income', TRUE, 'Black', 'Non-Hispanic', 'Male', FALSE, FALSE, TRUE),
('Hannah', 'Schmidt', 'Marie', 'codeminers4tw@gmail.com', '555-212-7788', '64 Ash Ct', 'Minneapolis', 'MN', '55401', 'Psychology', 'Clinical', 'Social Sciences', 'Senior', 'Part-Time', 3.40, 'In-State', 'Middle Income', FALSE, 'White', 'Non-Hispanic', 'Female', TRUE, FALSE, TRUE),
('Carlos', 'Rivera', 'Jose', 'codeminers4tw@gmail.com', '555-213-8899', '120 Magnolia St', 'Albuquerque', 'NM', '87101', 'Civil Engineering', NULL, 'Engineering', 'Sophomore', 'Full-Time', 3.15, 'In-State', 'Low Income', TRUE, 'White', 'Hispanic', 'Male', FALSE, FALSE, TRUE),
('Zoe', 'Thompson', NULL, 'codeminers4tw@gmail.com', '555-214-1122', '5 Willow Way', 'Nashville', 'TN', '37201', 'Music', 'Performance', 'Arts', 'Junior', 'Full-Time', 3.80, 'In-State', 'Middle Income', FALSE, 'Black', 'Non-Hispanic', 'Female', FALSE, FALSE, TRUE),
('Aiden', 'Clark', 'James', 'codeminers4tw@gmail.com', '555-215-3344', '72 Sycamore Rd', 'Phoenix', 'AZ', '85001', 'Computer Science', 'Software Engineering', 'Engineering', 'Freshman', 'Full-Time', 3.05, 'In-State', 'High Income', FALSE, 'White', 'Non-Hispanic', 'Male', FALSE, FALSE, FALSE),
('Jasmine', 'Robinson', 'Nicole', 'codeminers4tw@gmail.com', '555-216-5567', '39 Chestnut Ave', 'Baltimore', 'MD', '21201', 'Nursing', NULL, 'Health Sciences', 'Senior', 'Full-Time', 3.60, 'In-State', 'Low Income', TRUE, 'Black', 'Non-Hispanic', 'Female', FALSE, TRUE, TRUE),
('Noah', 'Anderson', NULL, 'codeminers4tw@gmail.com', '555-217-7789', '81 Redwood Ln', 'Denver', 'CO', '80201', 'Business Administration', 'Marketing', 'Business', 'Sophomore', 'Full-Time', 2.88, 'Out-of-State', 'Middle Income', FALSE, 'White', 'Non-Hispanic', 'Male', FALSE, FALSE, TRUE),
('Amara', 'Okonkwo', 'Chisom', 'codeminers4tw@gmail.com', '555-218-9900', '14 Cypress Blvd', 'Houston', 'TX', '77001', 'Biology', 'Genetics', 'Sciences', 'Junior', 'Full-Time', 3.95, 'In-State', 'Low Income', TRUE, 'Black', 'Non-Hispanic', 'Female', FALSE, FALSE, TRUE),
('Liam', 'Garcia', 'Eduardo', 'codeminers4tw@gmail.com', '555-219-2233', '96 Palm Dr', 'Los Angeles', 'CA', '90001', 'Film Studies', NULL, 'Arts', 'Senior', 'Part-Time', 3.30, 'In-State', 'Low Income', TRUE, 'White', 'Hispanic', 'Male', FALSE, FALSE, TRUE),
('Mei', 'Chen', 'Ling', 'codeminers4tw@gmail.com', '555-220-4455', '28 Bamboo St', 'San Francisco', 'CA', '94101', 'Computer Science', 'Data Science', 'Engineering', 'Junior', 'Full-Time', 3.75, 'In-State', 'Middle Income', FALSE, 'Asian', 'Non-Hispanic', 'Female', FALSE, FALSE, TRUE),
('Isaiah', 'Davis', NULL, 'codeminers4tw@gmail.com', '555-221-6677', '53 Ironwood Ct', 'Memphis', 'TN', '38101', 'Social Work', NULL, 'Social Sciences', 'Freshman', 'Full-Time', 2.72, 'In-State', 'Low Income', TRUE, 'Black', 'Non-Hispanic', 'Male', TRUE, FALSE, TRUE),
('Olivia', 'White', 'Grace', 'codeminers4tw@gmail.com', '555-222-8899', '7 Sequoia Ave', 'Charlotte', 'NC', '28201', 'Education', 'Elementary', 'Education', 'Sophomore', 'Full-Time', 3.48, 'In-State', 'Low Income', TRUE, 'White', 'Non-Hispanic', 'Female', FALSE, FALSE, TRUE),
('Marcus', 'Johnson', 'Tyler', 'codeminers4tw@gmail.com', '555-223-1234', '44 Birchwood Rd', 'St. Louis', 'MO', '63101', 'Mechanical Engineering', 'Robotics', 'Engineering', 'Senior', 'Full-Time', 3.20, 'In-State', 'Middle Income', FALSE, 'Black', 'Non-Hispanic', 'Male', FALSE, TRUE, TRUE),
('Elena', 'Romero', 'Isabel', 'codeminers4tw@gmail.com', '555-224-5678', '61 Acacia Ln', 'El Paso', 'TX', '79901', 'Nursing', 'Geriatrics', 'Health Sciences', 'Junior', 'Full-Time', 3.55, 'In-State', 'Low Income', TRUE, 'White', 'Hispanic', 'Female', FALSE, FALSE, TRUE),
('Jaylen', 'Harris', NULL, 'codeminers4tw@gmail.com', '555-225-9012', '23 Cottonwood Dr', 'Oakland', 'CA', '94601', 'Political Science', NULL, 'Social Sciences', 'Sophomore', 'Full-Time', 3.00, 'In-State', 'Low Income', TRUE, 'Black', 'Non-Hispanic', 'Male', FALSE, FALSE, TRUE);

-- 5 Fake Grants
INSERT INTO public.grants (grant_name, grantor, amount, due_date, minimum_gpa, academic_year, major_requirement, financial_need, residency, first_gen, race, ethnicity, gender, disability, military, manual_component, auto_apply, app_email, app_url) VALUES
('Future Health Leaders Grant', 'National Health Foundation', 2500.00, '2025-03-15', 3.50, NULL, 'Nursing', TRUE, NULL, FALSE, NULL, NULL, NULL, FALSE, FALSE, NULL, TRUE, 'codeminers4tw@gmail.com', 'https://nationalhealthfoundation.org/apply'),
('First Generation STEM Scholarship', 'TechForward Foundation', 3000.00, '2025-04-01', 3.00, NULL, 'Computer Science', TRUE, NULL, TRUE, NULL, NULL, NULL, FALSE, FALSE, 'Personal statement (500 words)', FALSE, NULL, 'https://techforward.org/scholarship'),
('Women in Engineering Award', 'Society of Women Engineers', 1500.00, '2025-05-30', 3.25, 'Junior', 'Mechanical Engineering', FALSE, NULL, FALSE, NULL, NULL, 'Female', FALSE, FALSE, NULL, TRUE, 'codeminers4tw@gmail.com', 'https://swe.org/awards'),
('Military Family Education Grant', 'American Veterans Association', 2000.00, '2025-06-15', NULL, NULL, NULL, TRUE, NULL, FALSE, NULL, NULL, NULL, FALSE, TRUE, NULL, TRUE, 'codeminers4tw@gmail.com', 'https://ava.org/education-grant'),
('Hispanic Heritage Scholarship', 'Latino Education Fund', 1750.00, '2025-04-20', 3.00, NULL, NULL, TRUE, NULL, FALSE, NULL, 'Hispanic', NULL, FALSE, FALSE, 'One letter of recommendation', FALSE, NULL, 'https://latinoeducationfund.org/scholarship');
